from find_path import Graph

g1 = Graph()
g1.ReadFile('plansza.txt')
g1.printNormal()
g1.PrintGraph()
print()
g2 = Graph()
g2.ReadFile('plansza2.txt')
g2.printNormal()
g2.PrintGraph()
print()
g3 = Graph()
g3.ReadFile('plansza3.txt')
g3.printNormal()
g3.PrintGraph()
